var tableauQuestion = [
    {   question : "Du kører 80 km/t og nærmer dig en by-zone, hvad gør du?",
        propositionA : "Jeg sætter farten op",
        propositionB : "Jeg sætter farten op, sålænge der ikke er andre biler",
        propositionC : "Jeg sætter farten ned",
        propositionD : "Jeg fortsætter med samme fart",
        reponse : "C"},
		
    {   question : "Du skal dreje til venstre i et lyskryds. I fodgængerfeltet ser du en fodgænger. Hvad gør du?",
        propositionA : "Jeg skynder mig at blæse forbi fodgængeren",
        propositionB : "Jeg venter indtil fodgængeren har passeret",
        propositionC : "Jeg kører fodgæneren ned",
        propositionD : "Jeg dytter af fodgængeren",
        reponse : "B"},
		
    {   question : "Medmindre andet er oplyst, er hastighedsgrænsen i by-zonen  ____  kmh.",
        propositionA : "50",
        propositionB : "60",
        propositionC : "70",
        propositionD : "80",
        reponse : "A"},
	
	{   question : "Du vil skifte vejbane, hvad gør du?",
        propositionA : "Jeg tjekker mine spejle",
        propositionB : "Jeg tjekker mine blinde vinkler",
        propositionC : "Jeg bruger mine blinklys",
        propositionD : "Jeg tjekker mine spejle, blinde vinkler og bruger mine blinklys",
        reponse : "D"},
		
	{   question : "Hvilken alkohol promille må man højest have i blodet mens man kører bil?",
        propositionA : "0.5‰",
        propositionB : "0.6‰",
        propositionC : "0.05‰",
        propositionD : "0.06‰",
        reponse : "A"},
		
	{   question : "Du vil holde en til siden for at hæve nogen penge. Langs vejkanten ser du en rød linje",
        propositionA : "Jeg må parkere langs vejen i ubegrænset tid",
        propositionB : "Jeg må standse langs vejen i 2 minutter",
        propositionC : "Jeg må standse langs vejen i 10 minutter",
        propositionD : "Jeg må hverken parkere eller standse her, så jeg finder et andet sted",
        reponse : "D"},
	
	{   question : "Hvornår skal der gives plads til udrykningskøretøjer?",
        propositionA : "Når de enten bruger sirene eller blink",
        propositionB : "Når de bruger langt lys",
        propositionC : "Altid",
        propositionD : "Når de bruger havariblink",
        reponse : "A"},
		
	{   question : "Du har indhentet den forankørende bil, der kører langsomt. Hvordan vil du fortsætte?",
        propositionA : "Jeg presser ham og får ham til at køre hurtigere",
        propositionB : "Jeg bremser hårdt",
        propositionC : "Jeg orienterer mig grundigt inden jeg overhaler",
        propositionD : "Jeg overhaler bare uden at se mig for",
        reponse : "C"},
		
	{   question : "Du kører på en motorvej med hastighedsgrænsen 130 km/t. De fleste i trafikken kører 140 km/t, hvordan vil du fortsætte?",
        propositionA : "Jeg sætter farten op så jeg kan følge med de andre bilister",
        propositionB : "Jeg holder den tilladte hastighedsgrænse på 130 km/t",
        propositionC : "Jeg sætter farten op så jeg kan overhale de andre bilister",
        propositionD : "Jeg sætter farten ned til 80 km/t",
        reponse : "B"},
		
	{   question : "Du holder stille og vil sætte i gang fra vejkanten. Hvordan vil du fortsætte?",
        propositionA : "Jeg sætter i gang med det samme.",
        propositionB : "Jeg er særlig opmærksom på modkørende.",
        propositionC : "Jeg giver tegn med blink og sætter i gang med det samme",
        propositionD : "Jeg drejer hovedet og ser, om der er frit bagude. Herefter giver jeg tegn med blink og sætter i gang",
        reponse : "D"},
]
